matrix:
  include:
    - language: node_js
      node_js: '10'

      script:
        - npm run lint
        - npm run build
        - npm run test
        - npm run docs

      deploy:
        # Deploy a new version of NPM package and create a Github release
        - provider: script
          skip_cleanup: true
          script: npx semantic-release

        # Deploy documentation to Github Pages
        # See https://docs.travis-ci.com/user/deployment/pages/
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          local-dir: built
          on:
            branch: master

    - dist: xenial
      language: python
      python: '3.7'

      install:
        - make -C py setup

      script:
        - make -C py lint
        - make -C py test

      deploy:
        provider: pypi
        user: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        server: https://https://test.pypi.org/legacy/
        on:
          tags: true

      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF py

    - language: r
      r: release

      r_binary_packages:
        - covr
        - lintr
        - roxygen
        - testthat

      script:
        - make -C r lint
        - make -C r test
        - make -C r build

      after_success:
        - cd r && Rscript -e 'covr::codecov()'
