title: Product
'@id': schema:Product
$extends: ../Thing.schema.yaml
role: tertiary
status: unstable
description: |
  Any offered product or service. For example: a pair of shoes; a concert ticket; the rental of a car; 
  a haircut; or an episode of a TV show streamed online. https://schema.org/Product
properties:
  brand:
    description: |
      Brand that the product is labelled with.
    type: sting
  productID:
    '@id': schema:productID
    description: |
      Product identification code.
    type: string
